##### WORKING SCA FROM CxFLOW GHA #####

# This workflow is to automate Checkmarx SCA scans.  It runs on a push to the main branch.
#
# The following GitHub Secrets must be first defined:
#   - CHECKMARX_SCA_USERNAME
#   - CHECKMARX_SCA_PASSWORD
#
# The following variables must be inserted below:
#   - <ProjectName>
#   - <SCATenant>
#   - <GitHubRepoUrl>
#
# For full documentation, including a list of all inputs, please refer to the README https://github.com/checkmarx-ts/checkmarx-cxflow-github-action

name: Checkmarx SCA Scan
on:
  push:
    branches:
      - main
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    # Runs a single command using the runners shell
    - name: Set SCA Resolver Enviroment
      run: "wget https://sca-downloads.s3.amazonaws.com/cli/1.10.4/ScaResolver-linux64.tar.gz && tar -xzvf ScaResolver-linux64.tar.gz && rm -rf ScaResolver-linux64.tar.gz"
      
    - name: Set Scala Packges
      run: "# remove old Bintray repo file && sudo rm -f /etc/yum.repos.d/bintray-rpm.repo || true && curl -L https://www.scala-sbt.org/sbt-rpm.repo > sbt-rpm.repo && sudo mv sbt-rpm.repo /etc/yum.repos.d/ && sudo yum install sbt"
      
    - name: Validate Scala
      run: "sbt --script-version"
      
      - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
        
    - name: Compile SCALA Project
      run: "cd ${{ github.workspace }} && sbt \"compile\" "
      
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.5 # GitHub Action version
      with:
        params: 
           --enable-sca-resolver=true
           --s ='${{ github.workspace }}'
           --n = '${{ github.repository }}'
           -a = '${{ secrets.SCA_TENANT }}'
           --u = '${{ secrets.SCA_USERNAME }}'
           --p '${{ secrets.SCA_PASSWORD }}'
              
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
      with:
          name: '${{ github.workspace }}/reports/'
      
